version: '3.1'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: '.env'
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "9091:5432"
