version: '3.1'
services:
  api:
    build: .
    command: npm run start:docker
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./src:/usr/app/src:ro
    env_file: '.env'

  db:
    image: postgres
    restart: always
    env_file: '.env'
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:80